name: ${rootProject.name}
main: ${group}.${rootProject.name}.${rootProject.name}Plugin
api-version: "1.13"
version: ${version}
website: https://www.spigotmc.org/resources/werewolves.35778/
description: ${description}
author: RFSMassacre
softdepend: [SkinsRestorer, Vampire, VampireRevamp, Multiverse-Core, GriefPrevention, WorldGuard]
commands:
  werewolf:
    aliases:
      - ww
    usage: /ww
    #permission: werewolf.werewolf
    default: true
  werewolfadmin:
    aliases:
      - wwa
    usage: /wwa
    #permission: werewolfadmin.werewolf
    default: true