name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
author: RFSMassacre
api-version: 1.13
softdepend: [SkinsRestorer, Vampire, VampireRevamp, Multiverse-Core, GriefPrevention, WorldGuard]
commands:
  werewolf:
    aliases:
      - ww
    usage: /ww
    #permission: werewolf.werewolf
    default: true
  werewolfadmin:
    aliases:
      - wwa
    usage: /wwa
    #permission: werewolfadmin.werewolf
    default: true